### ISSUE TITLE
Trailing / under windows

### ISSUE THREAD

**Issue by Meistercoach83** [DurgeshRathod/ai-test-gen-angular#1]
hey there! cool project, but I get an error when I try to use it under windows: 
In my project Dir I try to run node .\node_modules\ai-test-gen-angular\index.js src/app/app.component.ts tsconfig.json --read-from-index-files

but I get the following error: ERROR: tsconfig not present at root folder
 Error: Cannot find module '/tsconfig.json'

the trailing / shouldn´t be there, I think. Or am I wrong?

**Comment by yneeli-OSI** [comment]
I'm also getting the same error. Can you please help on this?

**Comment by durgesh-rathod-sf** [comment]
Try making it relative path starting with . (Dot) slash

**Comment by sandeepks1** [comment]
In your tsconfig if any comments are there then remove it,
