### ISSUE TITLE
GPT 429 ERROR

### ISSUE THREAD

**Issue by sandeepks1** [DurgeshRathod/ai-test-gen-angular#2]
RateLimitError: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

I am getting this error, I am using GPT4,to use this service do i need to buy some more limits

**Comment by durgesh-rathod-sf** [comment]
@sandeepks1 This issue is not related to ai-test-gen-angular
It is related to open ai usage limits in your open ai account. Please check your open ai account for billing and usage limits. :)
